### ISSUE TITLE
help with long metrics

### ISSUE THREAD

**Issue by iop3** [AmazingMech2418/AmazingMech2418#1]
Hi there!
Im a noob at github actions and stuff so can you tell me how to get the long metrics.

Help will be appreciated!

**Comment by firefish111** [comment]
i don't think he'll answer, i mean it's been 6 months he won't notice

**Comment by iop3** [comment]
oh lol can you help?

**Comment by firefish111** [comment]
wait

did i just misread minutes as months

i have the tiniest brain in the universe

**Comment by firefish111** [comment]
> Im a noob at github actions

um same problem over here

**Comment by iop3** [comment]
lol nvm then

**Comment by firefish111** [comment]
wait you're on replit?

**Comment by iop3** [comment]
yeah why

**Comment by firefish111** [comment]
i don't recognise your username

**Comment by iop3** [comment]
oh lul

**Comment by iop3** [comment]
i changed it

**Comment by firefish111** [comment]
aha that would explain it

**Comment by iop3** [comment]
;)

**Comment by AmazingMech2418** [comment]
@iop3 Honestly, I just found the repo and went from there with everything. LOL! I forgot what all I did though...

@firefish111 What has been 6 months?

**Comment by iop3** [comment]
~~:O amazingmech2418 appeared out of nowhere~~ oh it's okay lol

**Comment by firefish111** [comment]
> What has been 6 months?

The issue was six minutes old when i commented that and i misread minutes as months

**Comment by AmazingMech2418** [comment]
> > What has been 6 months?
> 
> The issue was six minutes old when i commented that and i misread minutes as months

Ah... LOL!

**Comment by firefish111** [comment]
qaz

**Comment by iop3** [comment]
qaz
