### ISSUE TITLE
> What has been 6 months?

### ISSUE THREAD

**Issue by iop3** [AmazingMech2418/AmazingMech2418#2]
> What has been 6 months?

The issue was six minutes old when i commented that and i misread minutes as months

_Originally posted by @firefish111 in https://github.com/AmazingMech2418/AmazingMech2418/issues/1#issuecomment-852354467_

**Comment by iop3** [comment]
i have no idea why i did this

**Comment by firefish111** [comment]
oh please just please

**Comment by iop3** [comment]
xD
